---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: source-test-scan-to-url
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: supply-chain
    app.kubernetes.io/part-of: source-test-scan-to-url
spec:
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
